### PR TITLE
Translation works

### PR DESCRIPTION
**Pull request by MuhdNurHidayat**
* Fixed missing translation function for `Digging (by chance)` in `api.lua`.
* Added Malay translation (translation is tested and worked correctly).

### CODE REVIEW

**Comment by SmallJoker** [comment]
Looks good, still seems to be up to date due to the slow development.

**Comment by MuhdNurHidayat** [comment]
oh, this is still open after 4 months... xD

**Comment by SmallJoker** [comment]
Needs conversion to the new gettext format.

**Comment by MuhdNurHidayat** [comment]
I'll open new PR later.

**Comment by MuhdNurHidayat** [comment]
I've completed the translation using the new gettext format.

I've opened new merge request on GitLab because this project is maintained by VanessaE which prefer GitLab over GitHub:
https://gitlab.com/VanessaE/unified_inventory/merge_requests/2

**Pull request closed without merging**
