### PR TITLE
Rounded formspec

### PR DESCRIPTION
**Pull request by SmallJoker**
The unified_inventory slots are rounded, and the gray tone looks a bit industrial. This PR attempts to change this by using a more transparent and darker theming. Opinions?

comparison

### CODE REVIEW

**Comment by Niklp-MT** [comment]
Looks good

**Comment by Niklp09** [comment]
time to merge

**Comment by debagos** [comment]
Looks refreshing, I like it.
It's a tad too round and too transparent in my opinion, but I will push this to my server anyway, because it looks nicer than the default look.
Good job :smiley:

**Comment by BuckarooBanzay** [comment]
LGTM :+1:

**Pull request merged**
